### ISSUE TITLE
Nox crashing on startup due to conflict with updated Fabric API and Nox's Embedded Library

### ISSUE THREAD

**Issue by LunexLunertic** [stormdirus2/nox#10]
So after I have updated my fabric API from version "fabric-api-0.46.0+1.18" to "fabric-api-0.46.1+1.18" and a couple of mods that I was using, Nox started to crash on startup, something about it pointing to the embedded library OmegaConfigGUI. 
Looking at the crash file at the bottom of the report it points to these mods being the cause: 

"Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes), Nox (nox)"

Now I know that it's not by Not Enough Crashes as that's not been updated but perhaps this has something to do with the updated fabric API causing the crash on startup with OmegaConfigGUI, here is my crash report file:

[crash-2022-01-17_21.28.04-server.txt](https://github.com/stormdirus2/nox/files/7886436/crash-2022-01-17_21.28.04-server.txt)

Nonetheless I love your mod, been having fun with the difficulty so far, made a couple of config changes though just to ease it up a little, and adding that with SIHYWTCAMD makes things feel quite challenging~

**Comment by AeiouEnigma** [comment]
I don't suppose you remember what the other mods are that you updated? You're using a large number of mods, and I know from experience that errors like this can point blame at mods that didn't actually cause the crash.

It would also be helpful if you could share your latest.log file from when this crash takes place.

**Comment by LunexLunertic** [comment]
Ok, I will see if isolating to only a few mods will cause a crash and record it.

Ok, so after testing and recording for almost 30mins, I have found the incompatible mod was Cave Tweaks for fabric:  [crash-2022-01-21_21.54.48-server.txt](https://github.com/stormdirus2/nox/files/7917722/crash-2022-01-21_21.54.48-server.txt)

Here's the log:  [latest.log](https://github.com/stormdirus2/nox/files/7917724/latest.log)

And I have recorded a video to show if the supposed crash comes from the latest update to fabric, turns out after checking the newest mods I have updated that the cause was from the mod "Cave Tweaks" being incompatible with Nox's Embedded Library "Omega Config" at least that's what the report says, I will link to it unlisted when I have it ready to show you mind that it is over 30 minutes long. I find the cause at around 30 minute mark so you won't have to sit and see the entire process of me testing which mod causes the crash.

**Comment by LunexLunertic** [comment]
Ok, here's the video, check at 28 minute mark where I find the actual culprit mod causing the crash: https://youtu.be/0We5quapzpU

**Comment by AeiouEnigma** [comment]
Have you tried updating CaveTweaks to version 1.2? You're using version 1.0 which was apparently a unified version for both Fabric and Forge. The day after CaveTweaks 1.0 was released, Starmute put out an update splitting the mod into separate downloads for Fabric and Forge, since apparently the unified version was causing crashes. I think there's a pretty good chance that CaveTweaks 1.0 caused other mods to not load properly, crashing the game.

CaveTweaks 1.2 seems to work just fine with Nox on my machine. But CaveTweaks 1.0 also seems to work fine with Nox. So if CaveTweaks is indeed your culprit, it may be breaking some other third mod which in turn makes Nox fail to load and crashes the game.

Also, in future comments, it would be fantastic if you could share a crash log from when the only loaded mods are Nox, Fabric API, and whatever mod causes the game to crash when used alongside Nox (and that mod's dependencies), since it's still unclear whether this crash is actually caused by Nox. Note that you should not install Omega Config, since it is included in Nox.

**Comment by LunexLunertic** [comment]
Sure thing, I did have CaveTweaks version 1.2 during that video, but like you said isolating those mods together didn't cause a crash, hmm, I will look further by what could possibly be the other mod that is causing the problem...

So, after looking at it, turns out it was some mod I have that has Mod Menu Embedded (Inventory Profiles Next) along with another mod that was perhaps using the deprecated Mod Menu API inside (also "deprecated custom value loading" as noted in the the changelog for version 3.0.1), along with myself having an outdated version of Mod Menu (I had version 3.0.0, and now updated it to 3.0.1) within my mods folder.

Apologies for that everything is now working just fine along with the all the mods now included, was strange that it wasn't pointing to this being the main cause but nonetheless there's no problems now.

So, this was just user error on my end, you can close this problem now that I figured out the main cause as now all mods are now working, I was simply unaware that there was a later version of Mod Menu.
